### ISSUE TITLE
No index is available for this BAM file

### ISSUE THREAD

**Issue by ramiromagno** [mdcao/capsim#4]
## Introduction

I guess I might be doing some wrong but I am getting "No index is available for this BAM file" error.

File listing:

```
GCF_000001405.26_GRCh38_genomic.dict       GCF_000001405.26_GRCh38_genomic.fna.fai        output.fastq.gz
GCF_000001405.26_GRCh38_genomic.fna        GCF_000001405.26_GRCh38_genomic.fna.rev.1.bt2  probes.bam
GCF_000001405.26_GRCh38_genomic.fna.1.bt2  GCF_000001405.26_GRCh38_genomic.fna.rev.2.bt2  probes.fasta
GCF_000001405.26_GRCh38_genomic.fna.2.bt2  GRCh38_header.txt                              probes.sam
GCF_000001405.26_GRCh38_genomic.fna.3.bt2  japsa                                          unaligned_reads.bam
GCF_000001405.26_GRCh38_genomic.fna.4.bt2  jsa.sim.capsim
```

## `jsa.sim.capsim` command that generates the error

```bash
./jsa.sim.capsim --reference GCF_000001405.26_GRCh38_genomic.fna --probe probes.bam --ID someid --fmedian 5000  --pacbio output --pblen 3000 --num 20000000
#Mark capturable regions
Exception in thread "main" htsjdk.samtools.SAMException: No index is available for this BAM file.
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:408)
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:924)
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:584)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:528)
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
	at japsa.tools.bio.sim.SimulateCaptureCmd.main(SimulateCaptureCmd.java:406)
```

**Comment by ramiromagno** [comment]
My mistake, a typo earlier...
